blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'blog'
urlpatterns = [
    # 순서에 따라 먼저 탐
    path('', views.ListView.as_view(), name='list'),
    path('json-response/', views.get_json_response),
    path('json-model-response/', views.ListArticles.as_view()),
    url(r'^write/$', login_required(views.WriteView.as_view()), name='write'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='view'),	# pk변수에 모든 값을 넣어 뷰로 전송하겠다는 뜻입니다. \d은 문자를 제외한 숫자
    url(r'^hello/$', views.hello),
    url(r'^view/(?P<pk>\d+)/remove/$', views.article_remove, name='article_remove'),
    
    url(r'^join/$', views.signup, name='join'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    # url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    # url(r'json/', views.jsonctrl),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    # 순서에 따라 먼저 탐
    path('', views.room, name='room'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'chat', include('chat.urls')),
    # url(r'^test/', include('blog.urls')),
]

# urlpatterns += static('/upload_files/', document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Article(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    image = models.ImageField(upload_to='%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='%Y/%m/%d/filtered')
    title = models.CharField(max_length=50)
    contents = models.TextField()	# 글자수 제한없는 긴 텍스트 
    url = models.URLField()
    # email  = models.EmailField()
    cdate = models.DateTimeField(auto_now_add=True)	# 날짜 시간

    # 어드민 리스트에서 노출될 이름으로 사용
    def __str__(self):
    	return '%s by %s' % (self.title, self.name_id)

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Article, self).delete(*args, **kwargs)

#class Choice(models.Model):
#    question = models.ForeignKey(Question, on_delete=models.CASCADE)
#    choice_text = models.CharField(max_length=200)
#    votes = models.IntegerField(default=0)

chat/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.forms import ModelForm
from blog.models import *
from django.contrib.auth.models import User

class Form(ModelForm):
	class Meta:
		model = Article
		fields=['title', 'contents', 'url','image']
		exclude = ('filtered_image', )

# 회원가입 폼
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

# 로그인폼
class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password'] # 로그인 시에는 유저이름과 비밀번호만 입력 받는다.

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from rest_framework.views import APIView
from rest_framework.response import Response
from . import serializers

import logging

logger = logging.getLogger(__name__)


from blog.forms import *

def hello(request):
	# print(reverse('blog:post_detail', args=[10]))
	logger.debug("list")
	return HttpResponse('hello')


def get_json_response(request):
	return JsonResponse({
		'message': 'JsonResponse 메세지',
		'title': 'JsonResponse 타이틀',
		 },
		json_dumps_params={'ensure_ascii': False})
	
class ListArticles(APIView):

    def get(self, request, format=None):
    	serializer = serializers.ArticleSerializer(Article.objects.all().order_by('cdate'), many=True)
    	return Response(data=serializer.data)

@login_required
def write(request):
	if request.method == 'POST':
		form = Form(request.POST, request.FILES)
		if form.is_valid():
			new_post = form.save(commit = False)
			new_post.user = request.user
			new_post = form.save()
			return redirect('/view/'+str(new_post.pk))
		else:
			return render(request, 'write.html',{'form' : form})
	else:
		form = Form()
		return render(request, 'write.html',{'form' : form})


class WriteView(generic.View):
	def post(self, request):
		form = Form(request.POST, request.FILES)
		if form.is_valid():
			new_post = form.save(commit = False)
			new_post.user = request.user
			new_post = form.save()
			return redirect('/view/'+str(new_post.pk))
		else:
			return render(request, 'write.html',{'form' : form})
	def get(self, request):
		form = Form()
		return render(request, 'write.html',{'form' : form})


class WriteFormView(generic.FormView):
	form_class = Form
	template_name = 'write.html'
	pk = None
	def form_valid(self, form):
		new_post = form.save(commit = False)
		new_post.user = self.request.user
		new_post = form.save()
		self.pk = new_post.pk
		return super(WriteFormView, self).form_valid(form)
	def get_success_url(self):
		return reverse('blog:view', kwargs={'pk': self.pk})

class ListView(generic.ListView):
	#print("here")
	context_object_name = 'articleList'
	template_name = 'list.html'
	def get_queryset(self): # 메소드 오버라이딩
		# c = q.choice_set.filter(choice_text__startswith='Just hacking')
		return Article.objects.all().order_by('cdate')

class DetailView(generic.DetailView):
	model = Article
	template_name = 'view.html'

@login_required
def article_remove(request, pk):
	article = get_object_or_404(Article, pk=pk)
	print(article.user)
	print(request.user)
	if article.user == request.user:
		article.delete()
		# comment.is_removed = True
		# comment.save()
	return redirect('blog:list')


def signup(request):
	if request.method == "POST":
		form = UserForm(request.POST)
		if form.is_valid():
			new_user = User.objects.create_user(**form.cleaned_data)
			django_login(request, new_user)
			return redirect('blog:list')
		else:
			# login_form.add_error(None, '아이디 또는 비밀번호가 올바르지 않습니다')
			return render(request, 'join.html', {'form': form})
	else:
		form = UserForm()
		return render(request, 'join.html', {'form': form})


def login(request):
	if request.method == "POST":
		form = LoginForm(request.POST)
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username = username, password = password)
		if user is not None:
			django_login(request, user)
			return redirect('blog:list')
		else:
			form.add_error(None, '아이디 또는 비밀번호가 올바르지 않습니다')
			return render(request, 'login.html', {'form': form})
	else:
		form = LoginForm()
		return render(request, 'login.html', {'form': form})


def logout(request):
	django_logout(request)
	return redirect('blog:list')

chat/views.py
from django.shortcuts import render

# Create your views here.
def room(request):
    context = {}
    return render(request, 'room.html', context)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Base</h1>
	{% block content %}
	{% endblock %}
</body>
</html>

blog/templates/join.html
{% extends 'base.html' %}

{% block content %}
	<h2>회원가입</h2>
    {% if form.errors %}
    	<p>{{ form.errors }}</p>
        <p>이미 이름이 존재합니다.</p>
    {% endif %}
	<form method="post" action="">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="회원가입" />
	</form>
{% endblock %}

blog/templates/list.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        {{ user.get_username }}님 환영합니다.  <a href="{%url 'blog:write' %}">작성</a>  <a href="{%url 'blog:logout' %}">로그아웃</a>  
    {% else %}
        <a href="{% url 'blog:login' %}">로그인</a>
        <a href="{% url 'blog:join' %}">회원가입</a>
    {% endif %}
	
	<li>제목| 저자 | 날짜
	{% for article in articleList %}
	<!-- <li><a href="/view/{{article.id}}"> {{ article.title }}</a> | {{ article.name }} | {{ article.cdate|date:"D d M Y"}}</li> -->
	<li><a href="{% url 'blog:view' article.id %}"> {{ article.title }}</a> | {{ article.user }} | {{ article.cdate|date:"D d M Y"}}</li>

	{% endfor %}
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="text-danger"><b>{{ error }}</b></p>
        {% endfor %}
    {% endif %}

    <form method="post" action="{% url 'blog:login' %}">
    {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

blog/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>View</title>
</head>
<body>
	제목 : {{ article.title }} 
	<br>
	저자 :  {{ article.user }} 
	<br>
	내용 : {{ article.contents}}
	<br>
	Email : {{ article.email}}
	<br>
    {% if article.cdate %}
        <div class="date">
            {{ article.cdate }}
        </div>
    {% endif %}
    {% if article.image %}
        <div class="date">
            <p><img style="width: 300px;height: 300px;" src="{{article.image.url}}" /></p>
        </div>
    {% endif %}
    <a class="btn btn-default" href="{% url 'blog:article_remove' pk=article.pk %}">삭제</a>
</body>
</html>

blog/templates/write.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>write</title>
</head>
<body>
	<form action="" method="post" enctype="multipart/form-data">
		{{ form.as_p }}
		{% csrf_token %}
		<button type="submit" class="btn btn-primary">저장</button>
	</form>
</body>
</html>

chat/templates/room.html
<!-- /templates/newapp/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
	// 클라이언트와 서버의 웹소켓 통신을 가능하도록 연결시켜주는 부분이다.
  	// 위에서 정의한 routing.py에서의 url과 일치하도록 해 주어야한다.
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/something/');
	// onmessage는 counsumers에서 보내는 메세지를 받는 부분이다.
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };
	// socket의 연결이 끊어지면 일어날 행동을 정의하는 부분이다.
    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>